name: Quant Scanner
on:
  schedule:
    - cron: "30 23-6 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Scanner
        run: python scanner.py
        env:
          GSPREAD_KEY: ${{ secrets.GSPREAD_KEY }}
