name: Quant Scanner
on:
  schedule:
    # 한국 시간(KST) 월~금 밤 23:30 ~ 새벽 06:30에 매 시간 실행되도록 UTC로 변환한 값
    - cron: "30 14 * * 1-5"
    - cron: "30 15-21 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Scanner
        run: python scanner.py
        env:
          GSPREAD_KEY: ${{ secrets.GSPREAD_KEY }}
